[package]
name = "nybbles"
version = "0.1.0"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
description = "Fast byte array to hex string conversion"
edition = "2021"
rust-version = "1.64"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "no-std"]
keywords = ["nibbles", "vector", "ethereum"]
homepage = "https://github.com/danipopes/nybbles"
repository = "https://github.com/danipopes/nybbles"
exclude = [".github/", "benches/", "fuzz/", "tests/"]

[dependencies]
smallvec = { version = "1.0", default-features = false, features = ["const_new", "union"] }
const-hex = { version = "1.10", default-features = false, features = ["alloc"] }

# serde
serde = { version = "1.0", optional = true, features = ["derive"] }

# rlp
alloy-rlp = { version = "0.3", default-features = false, optional = true }

# arbitrary
arbitrary = { version = "1.3", optional = true, default-features = false, features = ["derive"] }
proptest = { version = "1.4", optional = true, default-features = false, features = ["alloc"] }

[dev-dependencies]
hex-literal = "0.4"

[features]
default = ["std"]
std = ["const-hex/std", "serde?/std", "alloy-rlp?/std", "proptest?/std"]
serde = ["dep:serde", "smallvec/serde"]
rlp = ["dep:alloy-rlp"]
arbitrary = ["dep:arbitrary", "dep:proptest", "smallvec/arbitrary", "std"]
